// Mocks generated by Mockito 5.4.6 from annotations
// in list_rickandmorty_app/test/features/characters/presentation/viewmodels/character_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:list_rickandmorty_app/features/characters/domain/entities/character.dart'
    as _i5;
import 'package:list_rickandmorty_app/features/characters/domain/repositories/character_repository.dart'
    as _i2;
import 'package:list_rickandmorty_app/features/characters/domain/usecases/get_characters.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCharacterRepository_0 extends _i1.SmartFake
    implements _i2.CharacterRepository {
  _FakeCharacterRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetCharacters].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCharacters extends _i1.Mock implements _i3.GetCharacters {
  MockGetCharacters() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CharacterRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCharacterRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CharacterRepository);

  @override
  _i4.Future<List<_i5.Character>> call({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#page: page}),
            returnValue: _i4.Future<List<_i5.Character>>.value(
              <_i5.Character>[],
            ),
          )
          as _i4.Future<List<_i5.Character>>);
}
