name: Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Executar Testes
    runs-on: ubuntu-latest
    
    steps:
      # 1. Baixar o código
      - name: Baixar código
        uses: actions/checkout@v4
        
      # 2. Instalar Flutter
      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          
      # 3. Instalar dependências
      - name: Instalar dependências
        run: flutter pub get
        
      # 4. Verificar formatação
      - name: Verificar formatação
        run: dart format --output=none --set-exit-if-changed .
        
      # 5. Analisar código
      - name: Analisar código
        run: flutter analyze
        
      # 6. Executar testes
      - name: Executar testes
        run: flutter test --coverage
        
      # 7. Verificar cobertura
      - name: Verificar cobertura
        run: |
          echo "Cobertura de testes:"
          lcov --summary coverage/lcov.info
          
      # 8. Salvar relatório
      - name: Salvar relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-cobertura
          path: coverage/ 