name: CI - Testes Automatizados

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Executar Testes
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        
      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'
          
      - name: Instalar dependências
        run: flutter pub get
        
      - name: Verificar formatação
        run: dart format --output=none --set-exit-if-changed .
        
      - name: Analisar código
        run: flutter analyze
        
      - name: Executar todos os testes
        run: flutter test --coverage
        
      - name: Gerar relatório de cobertura
        run: |
          genhtml coverage/lcov.info -o coverage/html
          echo "Cobertura de testes gerada em coverage/html/"
          
      - name: Upload relatório de cobertura
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/html/
          
      - name: Verificar cobertura mínima
        run: |
          # Verificar se a cobertura está acima de 80%
          COVERAGE=$(lcov --summary coverage/lcov.info | grep "lines" | cut -d ' ' -f 4 | cut -d '%' -f 1)
          echo "Cobertura atual: $COVERAGE%"
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "❌ Cobertura abaixo de 80%"
            exit 1
          else
            echo "✅ Cobertura OK: $COVERAGE%"
          fi 