name: Performance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1' # Toda segunda-feira às 2h

jobs:
  performance:
    name: Performance Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Run performance tests
        run: |
          # Teste de tempo de inicialização
          time flutter test --coverage
          
          # Teste de memória
          flutter test --coverage --dart-define=FLUTTER_TEST_MEMORY_LEAK=true
          
      - name: Generate performance report
        run: |
          echo "Performance Test Results" > performance_report.md
          echo "=========================" >> performance_report.md
          echo "" >> performance_report.md
          echo "Test execution time: $(date)" >> performance_report.md
          echo "Flutter version: $(flutter --version)" >> performance_report.md
          
      - name: Upload performance report
        uses: actions/upload-artifact@v3
        with:
          name: performance-report
          path: performance_report.md

  load-test:
    name: Load Testing
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Run load tests
        run: |
          # Executar testes múltiplas vezes para simular carga
          for i in {1..5}; do
            echo "Running test iteration $i"
            flutter test --coverage
          done
          
      - name: Analyze load test results
        run: |
          echo "Load Test Results" > load_test_report.md
          echo "==================" >> load_test_report.md
          echo "" >> load_test_report.md
          echo "Multiple test iterations completed successfully" >> load_test_report.md
          
      - name: Upload load test report
        uses: actions/upload-artifact@v3
        with:
          name: load-test-report
          path: load_test_report.md 